In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
import numpy as np

In [5]:
np.__version__

'2.4.0'

In [6]:
titanic_df = pd.read_csv("titanic_data.csv" , delimiter = "," , header = 0)

In [7]:
titanic_df.shape

(891, 12)

In [8]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
name = titanic_df["Name"]
name

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [12]:
type(name)

pandas.core.series.Series

In [13]:
name_age = titanic_df[["Name","Age"]]
name_age

Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [16]:
name_age.loc[2,"Age"]

np.float64(26.0)

In [19]:
name_age.loc[2:10,]

Name   Age
2                              Heikkinen, Miss. Laina  26.0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                            Allen, Mr. William Henry  35.0
5                                    Moran, Mr. James   NaN
6                             McCarthy, Mr. Timothy J  54.0
7                      Palsson, Master. Gosta Leonard   2.0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                 Nasser, Mrs. Nicholas (Adele Achem)  14.0
10                    Sandstrom, Miss. Marguerite Rut   4.0

In [20]:
name_age.loc[2,]

Name    Heikkinen, Miss. Laina
Age                       26.0
Name: 2, dtype: object

In [21]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [22]:
titanic_df.shape

(891, 12)

In [23]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [24]:
titanic_df.head(8)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S

In [25]:
titanic_df.tail(8)

PassengerId  Survived  Pclass                                      Name  \
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket    Fare Cabin Embarked  
883    male  28.0      0      0  C.A./SOTON 34068  10.500   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.050   NaN        S  
885  female  39.0      0      5            382652  29.125   NaN        Q  
886    male  27.0      0      0            211536  13.000   NaN        S  
887  female  19.0      0      0            112053  30.000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.450   NaN        S  
889    male  26.0      0      0            111369  30.000  C148        C  
890    male  32.0      0      0            370376   7.750   NaN        Q

In [26]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [29]:
mask = titanic_df["Fare"] > 100

In [30]:
fare_100 = titanic_df[mask]

In [31]:
fare_100

PassengerId  Survived  Pclass  \
27            28         0       1   
31            32         1       1   
88            89         1       1   
118          119         0       1   
195          196         1       1   
215          216         1       1   
258          259         1       1   
268          269         1       1   
269          270         1       1   
297          298         0       1   
299          300         1       1   
305          306         1       1   
306          307         1       1   
307          308         1       1   
311          312         1       1   
318          319         1       1   
319          320         1       1   
325          326         1       1   
332          333         0       1   
334          335         1       1   
337          338         1       1   
341          342         1       1   
373          374         0       1   
377          378         0       1   
380          381         1       1   
390          391         1       1   
393          394         1       1   
435          436         1       1   
438          439         0       1   
498          499         0       1   
505          506         0       1   
527          528         0       1   
537          538         1       1   
544          545         0       1   
550          551         1       1   
557          558         0       1   
581          582         1       1   
609          610         1       1   
659          660         0       1   
660          661         1       1   
679          680         1       1   
689          690         1       1   
698          699         0       1   
700          701         1       1   
708          709         1       1   
716          717         1       1   
730          731         1       1   
737          738         1       1   
742          743         1       1   
763          764         1       1   
779          780         1       1   
802          803         1       1   
856          857         1       1   

                                                  Name     Sex    Age  SibSp  \
27                      Fortune, Mr. Charles Alexander    male  19.00      3   
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1   
88                          Fortune, Miss. Mabel Helen  female  23.00      3   
118                           Baxter, Mr. Quigg Edmond    male  24.00      0   
195                               Lurette, Miss. Elise  female  58.00      0   
215                            Newell, Miss. Madeleine  female  31.00      1   
258                                   Ward, Miss. Anna  female  35.00      0   
268      Graham, Mrs. William Thompson (Edith Junkins)  female  58.00      0   
269                             Bissette, Miss. Amelia  female  35.00      0   
297                       Allison, Miss. Helen Loraine  female   2.00      1   
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.00      0   
305                     Allison, Master. Hudson Trevor    male   0.92      1   
306                            Fleming, Miss. Margaret  female    NaN      0   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.00      1   
311                         Ryerson, Miss. Emily Borie  female  18.00      2   
318                           Wick, Miss. Mary Natalie  female  31.00      0   
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  female  40.00      1   
325                           Young, Miss. Marie Grice  female  36.00      0   
332                          Graham, Mr. George Edward    male  38.00      0   
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  female    NaN      1   
337                    Burns, Miss. Elizabeth Margaret  female  41.00      0   
341                     Fortune, Miss. Alice Elizabeth  female  24.00      3   
373                                Ringhini, Mr. Sante    male  22.00      0   
377                          Wid

In [34]:
female_fare_100 = fare_100[fare_100.Sex == "female"]

In [35]:
female_fare_100

PassengerId  Survived  Pclass  \
31            32         1       1   
88            89         1       1   
195          196         1       1   
215          216         1       1   
258          259         1       1   
268          269         1       1   
269          270         1       1   
297          298         0       1   
299          300         1       1   
306          307         1       1   
307          308         1       1   
311          312         1       1   
318          319         1       1   
319          320         1       1   
325          326         1       1   
334          335         1       1   
337          338         1       1   
341          342         1       1   
380          381         1       1   
393          394         1       1   
435          436         1       1   
498          499         0       1   
537          538         1       1   
581          582         1       1   
609          610         1       1   
689          690         1       1   
700          701         1       1   
708          709         1       1   
716          717         1       1   
730          731         1       1   
742          743         1       1   
763          764         1       1   
779          780         1       1   
856          857         1       1   

                                                  Name     Sex   Age  SibSp  \
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
88                          Fortune, Miss. Mabel Helen  female  23.0      3   
195                               Lurette, Miss. Elise  female  58.0      0   
215                            Newell, Miss. Madeleine  female  31.0      1   
258                                   Ward, Miss. Anna  female  35.0      0   
268      Graham, Mrs. William Thompson (Edith Junkins)  female  58.0      0   
269                             Bissette, Miss. Amelia  female  35.0      0   
297                       Allison, Miss. Helen Loraine  female   2.0      1   
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.0      0   
306                            Fleming, Miss. Margaret  female   NaN      0   
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1   
311                         Ryerson, Miss. Emily Borie  female  18.0      2   
318                           Wick, Miss. Mary Natalie  female  31.0      0   
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  female  40.0      1   
325                           Young, Miss. Marie Grice  female  36.0      0   
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  female   NaN      1   
337                    Burns, Miss. Elizabeth Margaret  female  41.0      0   
341                     Fortune, Miss. Alice Elizabeth  female  24.0      3   
380                              Bidois, Miss. Rosalie  female  42.0      0   
393                             Newell, Miss. Marjorie  female  23.0      1   
435                          Carter, Miss. Lucile Polk  female  14.0      1   
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0      1   
537                                LeRoy, Miss. Bertha  female  30.0      0   
581  Thayer, Mrs. John Borland (Marian Longstreth M...  female  39.0      1   
609                          Shutes, Miss. Elizabeth W  female  40.0      0   
689                  Madill, Miss. Georgette Alexandra  female  15.0      0   
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female  18.0      1   
708                               Cleaver, Miss. Alice  female  22.0      0   
716                      Endres, Miss. Caroline Louise  female  38.0      0   
730                      Allen, Miss. Elisabeth Walton  female  29.0      0   
742              Ryerson, Miss. Susan Parker "Suzette"  female  21.0      2   
763          Carter, Mrs. William Ernest (Lucile Polk)  female  36.0      1   
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  female  43.

In [36]:
female_fare_100.shape

(34, 12)

In [38]:
female_fare_100 = titanic_df[
    (titanic_df["Fare"] > 100) & (titanic_df["Sex"] == "female")
]
female_fare_100.head()

PassengerId  Survived  Pclass  \
31            32         1       1   
88            89         1       1   
195          196         1       1   
215          216         1       1   
258          259         1       1   

                                               Name     Sex   Age  SibSp  \
31   Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
88                       Fortune, Miss. Mabel Helen  female  23.0      3   
195                            Lurette, Miss. Elise  female  58.0      0   
215                         Newell, Miss. Madeleine  female  31.0      1   
258                                Ward, Miss. Anna  female  35.0      0   

     Parch    Ticket      Fare        Cabin Embarked  
31       0  PC 17569  146.5208          B78        C  
88       2     19950  263.0000  C23 C25 C27        S  
195      0  PC 17569  146.5208          B80        C  
215      0     35273  113.2750          D36        C  
258      0  PC 17755  512.3292          NaN        C

In [39]:
female_fare_100 = titanic_df[
    (titanic_df.Fare > 100) & (titanic_df.Sex == "female")
]
female_fare_100.head()

PassengerId  Survived  Pclass  \
31            32         1       1   
88            89         1       1   
195          196         1       1   
215          216         1       1   
258          259         1       1   

                                               Name     Sex   Age  SibSp  \
31   Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN      1   
88                       Fortune, Miss. Mabel Helen  female  23.0      3   
195                            Lurette, Miss. Elise  female  58.0      0   
215                         Newell, Miss. Madeleine  female  31.0      1   
258                                Ward, Miss. Anna  female  35.0      0   

     Parch    Ticket      Fare        Cabin Embarked  
31       0  PC 17569  146.5208          B78        C  
88       2     19950  263.0000  C23 C25 C27        S  
195      0  PC 17569  146.5208          B80        C  
215      0     35273  113.2750          D36        C  
258      0  PC 17755  512.3292          NaN        C

female, survived

In [47]:
female_survived = titanic_df[
 (titanic_df.Survived == 1 ) & (titanic_df.Sex == "female")
    ]
female_survived.head()

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

total survived

In [48]:
survived = titanic_df[
 (titanic_df.Survived == 1 ) 
    ]
survived.head(10)

PassengerId  Survived  Pclass  \
1             2         1       1   
2             3         1       3   
3             4         1       1   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
15           16         1       2   
17           18         1       2   
19           20         1       3   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
17                       Williams, Mr. Charles Eugene    male   NaN      0   
19                            Masselmani, Mrs. Fatima  female   NaN      0   

    Parch            Ticket     Fare Cabin Embarked  
1       0          PC 17599  71.2833   C85        C  
2       0  STON/O2. 3101282   7.9250   NaN        S  
3       0            113803  53.1000  C123        S  
8       2            347742  11.1333   NaN        S  
9       0            237736  30.0708   NaN        C  
10      1           PP 9549  16.7000    G6        S  
11      0            113783  26.5500  C103        S  
15      0            248706  16.0000   NaN        S  
17      0            244373  13.0000   NaN        S  
19      0              2649   7.2250   NaN        C

In [49]:
female_survived = titanic_df[
(titanic_df.Sex == "female")  &  (titanic_df.Survived == 1 )
    ]
female_survived.shape

(233, 12)

Out of 891 passengers , 233 female passengers survived 

In [51]:
null_cabin = titanic_df[titanic_df.Cabin.isna()]

In [53]:
null_cabin.shape

(687, 12)

In [55]:
titanic_df['Ticket'].duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Ticket, Length: 891, dtype: bool